name: NPCLibPLus
version: ${project.version}
main: me.marc_val_96.npclib.NPC
load: STARTUP
softdepend: [ProtocolLib]
authors: [Marc_val_96]
description: NPC's For 1.15
commands:
  npclib:
    description: Test the Lib
